### PR TITLE
Implement cbow

### PR DESCRIPTION
**Pull request by arkainoh**
Complete implementing the basic structure of CBOW model.
It still needs validation and enhancement in computational complexity.

### CODE REVIEW

**Comment by arkainoh** [comment]
It is necessary to apply hierarchical softmax when updating W_o

**Comment by YeonJaemin** [comment]
굉장합니다!

**Comment by YeonJaemin** [comment]
great!

**Review by YeonJaemin — APPROVED** [review]
Great code :) Let's make this more efficient

**Pull request merged**
